/*
 * Generated by ISE 7.3.9.2766 GPL Edition - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F217_6123();
extern void F219_6274();
extern void F224_6343();
extern void F225_6481();
extern void F242_3461();
extern void F241_6008();
extern void F53_1185();
extern EIF_REFERENCE F53_1172();
extern EIF_BOOLEAN F53_1184();
extern EIF_BOOLEAN F53_1189();
extern void F53_1194();
extern void F53_1195();
extern void F53_1196();
extern void F46_1109();
extern EIF_TYPED_VALUE F46_1110();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F217_6123;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F224_6343;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F242_3461;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F219_6274;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F225_6481;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F241_6008;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F53_1185;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F53_1184;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F53_1172;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F53_1189;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F53_1194;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F53_1195;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F53_1196;

	egc_str_dtype = 218;

	egc_str32_dtype = 224;
	egc_arr_dtype = 241;
	egc_tup_dtype = 172;
	egc_disp_rout_id = 2624;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)591;
	egc_sp_wchar = (EIF_TYPE_INDEX)783;
	egc_sp_bool = (EIF_TYPE_INDEX)391;
	egc_sp_uint8 = (EIF_TYPE_INDEX)706;
	egc_sp_uint16 = (EIF_TYPE_INDEX)673;
	egc_sp_uint32 = (EIF_TYPE_INDEX)423;
	egc_sp_uint64 = (EIF_TYPE_INDEX)439;
	egc_sp_int8 = (EIF_TYPE_INDEX)556;
	egc_sp_int16 = (EIF_TYPE_INDEX)746;
	egc_sp_int32 = (EIF_TYPE_INDEX)294;
	egc_sp_int64 = (EIF_TYPE_INDEX)469;
	egc_sp_real32 = (EIF_TYPE_INDEX)609;
	egc_sp_real64 = (EIF_TYPE_INDEX)330;
	egc_sp_pointer = (EIF_TYPE_INDEX)499;
	egc_sp_ref = (EIF_TYPE_INDEX)255;

	egc_uint8_ref_dtype = 194;
	egc_uint16_ref_dtype = 200;
	egc_uint32_ref_dtype = 197;
	egc_uint64_ref_dtype = 209;
	egc_int8_ref_dtype = 173;
	egc_int16_ref_dtype = 206;
	egc_int32_ref_dtype = 203;
	egc_int64_ref_dtype = 185;
	egc_bool_ref_dtype = 188;
	egc_real32_ref_dtype = 176;
	egc_char_ref_dtype = 182;
	egc_wchar_ref_dtype = 179;
	egc_real64_ref_dtype = 191;
	egc_point_ref_dtype = 212;

	egc_uint8_dtype = 195;
	egc_uint16_dtype = 201;
	egc_uint32_dtype = 198;
	egc_uint64_dtype = 210;
	egc_int8_dtype = 174;
	egc_int16_dtype = 207;
	egc_int32_dtype = 204;
	egc_int64_dtype = 186;
	egc_bool_dtype = 189;
	egc_real32_dtype = 177;
	egc_char_dtype = 183;
	egc_wchar_dtype = 180;
	egc_real64_dtype = 192;
	egc_point_dtype = 213;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 64;
	egc_except_emnger_dtype = 52;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;

	egc_fcall = egc_fcall_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "networktest_server";
	egc_system_location = "C:\\Users\\Stefan Rasmussen\\Desktop\\networktest\\networktest_server\\EIFGENs\\networktest_server\\W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1383045441;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 880;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcorigin = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcoffset = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcorigin[0] = 340;
	egc_rcoffset[0] = 1;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 45;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F46_1109;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F46_1110;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 870; /* APPLICATION */
	}
}

#ifdef __cplusplus
}
#endif
